Fixed a bug in samples/calendarExample.py that would cause execution to fail when an event attendee does not have any attendeeStatus data.
This error was characterized by the following stack trace:

Traceback (most recent call last):
  File "calendarExample.py", line 577, in <module>
    main()
  File "calendarExample.py", line 574, in main
    sample.Run(delete)
  File "calendarExample.py", line 498, in Run
    self._PrintAllEventsOnDefaultCalendar()
  File "calendarExample.py", line 99, in _PrintAllEventsOnDefaultCalendar
    print '\t\t\t%s' % (a_participant.attendee_status.value,)
AttributeError: 'NoneType' object has no attribute 'value'

This resolves issue #80.

--HG--
extra : convert_revision : svn%3A7ed92db3-4423-0410-a5bc-5f2579731264/trunk%40615